"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import SiteNav from "../../SiteNav";
type Setup = { id:string; name:string; category:"seryjny"|"sport"|"wyścig"; cc:string; carb:string; exhaust:string; rpm:string; notes:string; parts:string[] };
const setups:Setup[] = [
{id:"50-stock",name:"50 cm³ — punkt wyjścia",category:"seryjny",cc:"50 cm³",carb:"14–17 mm",exhaust:"Seryjny, dopasowany do silnika",rpm:"6 000–8 000",notes:"Konfiguracja referencyjna do codziennej jazdy. Najpierw sprawdź stan cylindra, szczelność i ustawienia producenta.",parts:["Cylinder seryjny","Gaźnik w specyfikacji OEM","Seryjny airbox","Przełożenia fabryczne"]},
{id:"50-sport",name:"50 cm³ — łagodny sport",category:"sport",cc:"50 cm³",carb:"17–19 mm",exhaust:"Sportowy, zakres średnich obrotów",rpm:"7 000–9 500",notes:"Przykładowy kierunek konfiguracji, nie gotowa recepta. Dobór gaźnika i dysz zależy od konkretnego modelu oraz wydechu.",parts:["Sprawny cylinder seryjny","Wydech sportowy do pojemności","Regulacja gaźnika po zmianach","Kontrola świecy i temperatury"]},
{id:"70-sport",name:"70 cm³ — sport / ulica",category:"sport",cc:"70 cm³",carb:"19–24 mm",exhaust:"Komora sportowa dopasowana do port timingu",rpm:"8 000–10 500",notes:"Zacznij od danych producenta cylindra i wydechu. Sama większa średnica gaźnika nie gwarantuje wzrostu mocy.",parts:["Zestaw 70 cm³","Wydech z zakresem zgodnym z cylindrem","Gaźnik dobrany do zestawu","Weryfikacja chłodzenia i smarowania"]},
{id:"70-race",name:"70 cm³ — wysokie obroty",category:"wyścig",cc:"70 cm³",carb:"24–28 mm",exhaust:"Wydech wyścigowy o wąskim zakresie",rpm:"9 500–12 000",notes:"Wyłącznie jako punkt do dalszych obliczeń i walidacji. Wysokie obroty zwiększają wymagania wobec korbowodu, łożysk, chłodzenia i strojenia.",parts:["Cylinder wyścigowy z kartą techniczną","Wydech pod kąty otwarcia portów","Gaźnik według specyfikacji zestawu","Pomiar na hamowni i kontrola temperatury"]},
{id:"80-sport",name:"80 cm³ — elastyczny setup",category:"sport",cc:"80 cm³",carb:"21–26 mm",exhaust:"Komora nastawiona na szeroki zakres",rpm:"7 500–10 000",notes:"Szukaj dopasowania całego zestawu. Port timing i charakterystyka komory są ważniejsze niż dobór części wyłącznie według pojemności.",parts:["Cylinder 80 cm³","Komora o szerokim zakresie","Dolot i gaźnik zgodne z producentem","Sprawdzenie sprzęgła i przełożeń"]},
{id:"custom",name:"Projekt własny",category:"wyścig",cc:"dowolna",carb:"według obliczeń",exhaust:"Wyliczony w 2T Exhaust Lab",rpm:"według port timingu",notes:"Użyj kalkulatora wydechu jako szkicu geometrii, a następnie porównaj wynik z dokumentacją cylindra i pomiarami.",parts:["Zmierz bore i stroke","Ustal kąty otwarcia i zamknięcia wydechu","Oblicz komorę","Zapisz wyniki testów i poprawki"]}
];
const categoryLabel:Record<Setup["category"],string>={seryjny:"Seryjny",sport:"Sport",wyścig:"Wyścigowy"};
export default function SetupsPage(){
 const [filter,setFilter]=useState("wszystkie"),[query,setQuery]=useState(""),[saved,setSaved]=useState<string[]>([]);
 const shown=useMemo(()=>setups.filter(s=>(filter==="wszystkie"||s.category===filter)&&(s.name+" "+s.cc+" "+s.exhaust+" "+s.notes+" "+s.parts.join(" ")).toLowerCase().includes(query.toLowerCase())),[filter,query]);
 return <main className="min-h-screen bg-[#090909] text-white"><div className="mx-auto max-w-7xl px-5 py-5 lg:px-8"><SiteNav/>
 <div className="mt-8"><Link href="/narzedzia" className="text-sm text-zinc-500 hover:text-white">← Narzędzia</Link><p className="mt-5 text-xs font-black uppercase tracking-[.3em] text-red-500">MotoHub / Baza</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Baza setupów 2T</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">Przykładowe konfiguracje startowe do porównania i dalszej weryfikacji. Zakresy są orientacyjne — zawsze pierwszeństwo ma dokumentacja konkretnego cylindra, gaźnika i wydechu.</p></div>
 <div className="mt-7 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj po pojemności, części, opisie…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm outline-none focus:border-red-500/50"/><div className="flex flex-wrap gap-2">{[["wszystkie","Wszystkie"],["seryjny","Seryjne"],["sport","Sport"],["wyścig","Wyścigowe"]].map(([value,label])=><button type="button" key={value} onClick={()=>setFilter(value)} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(filter===value?"border-red-500/40 bg-red-500/15 text-red-200":"border-white/10 bg-white/[.03] text-zinc-400 hover:text-white")}>{label}</button>)}</div></div>
 <div className="mt-5 flex items-center justify-between text-xs text-zinc-500"><span>Znaleziono: {shown.length}</span><span>Zapisane w tej sesji: {saved.length}</span></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2">{shown.map(s=><article key={s.id} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-lg border border-white/10 px-2 py-1 text-[10px] uppercase tracking-wider text-zinc-400">{categoryLabel[s.category]}</span><h2 className="mt-3 text-xl font-bold">{s.name}</h2></div><button type="button" onClick={()=>setSaved(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])} className={"rounded-xl border px-3 py-2 text-xs font-semibold "+(saved.includes(s.id)?"border-red-500/40 bg-red-500/10 text-red-200":"border-white/10 text-zinc-400 hover:text-white")}>{saved.includes(s.id)?"✓ Zapisano":"☆ Zapisz"}</button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/25 p-3"><p className="text-[10px] uppercase text-zinc-500">Pojemność</p><p className="mt-1 text-sm font-semibold">{s.cc}</p></div><div className="rounded-xl bg-black/25 p-3"><p className="text-[10px] uppercase text-zinc-500">Orientacyjne obroty</p><p className="mt-1 text-sm font-semibold">{s.rpm}</p></div><div className="rounded-xl bg-black/25 p-3"><p className="text-[10px] uppercase text-zinc-500">Gaźnik</p><p className="mt-1 text-sm font-semibold">{s.carb}</p></div><div className="rounded-xl bg-black/25 p-3"><p className="text-[10px] uppercase text-zinc-500">Wydech</p><p className="mt-1 text-sm font-semibold">{s.exhaust}</p></div></div><p className="mt-4 text-sm leading-6 text-zinc-400">{s.notes}</p><div className="mt-4 border-t border-white/10 pt-4"><p className="text-xs font-bold text-zinc-300">Lista kontrolna</p><ul className="mt-2 grid gap-2 sm:grid-cols-2">{s.parts.map(part=><li key={part} className="flex gap-2 text-xs text-zinc-500"><span className="text-red-400">•</span>{part}</li>)}</ul></div></article>)}</div>
 {shown.length===0&&<div className="mt-5 rounded-2xl border border-white/10 p-8 text-center text-sm text-zinc-500">Brak wyników. Zmień wyszukiwaną frazę lub filtr.</div>}
 <div className="mt-6 rounded-2xl border border-amber-500/20 bg-amber-500/[.04] p-4 text-xs leading-5 text-amber-100/80"><b>Ważne:</b> to nie są zweryfikowane receptury ani gwarancja mocy. Nie kopiuj dysz czy ustawień bez strojenia dla swojego silnika. Przestrzegaj lokalnych przepisów i używaj pojazdu zgodnie z jego przeznaczeniem.</div>
 <div className="mt-5 flex flex-wrap gap-3"><Link href="/narzedzia/kalkulator" className="rounded-xl bg-red-500 px-4 py-3 text-sm font-bold text-white hover:bg-red-400">Otwórz kalkulator wydechu →</Link><Link href="/narzedzia/tuning-2t" className="rounded-xl border border-white/10 px-4 py-3 text-sm font-bold text-zinc-300 hover:bg-white/5">Symulator mocy i obrotów →</Link></div>
 </div></main>;
}
