"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import SiteNav from "../../SiteNav";

type Engine = "AM6" | "Derbi D50B0" | "Piaggio Hi-Per2" | "Minarelli poziomy" | "Minarelli pionowy" | "Peugeot 2T" | "Honda Dio AF18/AF27" | "Simson M5x1";
type Goal = "street" | "mid" | "race";
type PortProfile = { id:string; name:string; engine:Engine; family:string; bore:string; note:string; exhaust:string; intake:string; crank:string; case:string; };
const profiles:PortProfile[] = [
  {id:"am6-oem",name:"OEM 50 cm³",engine:"AM6",family:"Fabryczny",bore:"50 cm³",note:"Plan kontroli i przywrócenia fabrycznej specyfikacji.",exhaust:"Sprawdź zgodność z dokumentacją i stan powierzchni.",intake:"Szczelność króćca, membrany i uszczelek.",crank:"Kontrola luzów, bicia i łożysk przez kompetentny serwis.",case:"Bez zmian przy zwykłym serwisie."},
  {id:"am6-sport",name:"Sport / 50–70 cm³",engine:"AM6",family:"Sport",bore:"Zależnie od SKU",note:"Najpierw potwierdź, czy producent dopuszcza obróbkę tego cylindra.",exhaust:"Dobierz tylko według dokładnego SKU i zakresu pracy producenta.",intake:"Zweryfikuj zgodność gaźnika, króćca i membrany.",crank:"Postępuj zgodnie z limitem obrotów i wymogami producenta.",case:"Nie zakładaj, że potrzebne jest powiększanie karterów."},
  {id:"am6-race",name:"High-end / wyścigowy",engine:"AM6",family:"Tor",bore:"Zależnie od SKU i skoku",note:"Brak uniwersalnych wymiarów. Potrzebna dokumentacja konkretnej sztuki.",exhaust:"Charakterystyka komory musi być zgodna z dokumentacją cylindra.",intake:"Sprawdź wymagania dotyczące przepływu i podzespołów.",crank:"Weryfikacja zestawu, łożyskowania i limitu obrotów przez specjalistę.",case:"Tylko po sprawdzeniu geometrii i zaleceń producenta."},
  {id:"derbi-oem",name:"OEM 50 cm³",engine:"Derbi D50B0",family:"Fabryczny",bore:"50 cm³",note:"Skup się na specyfikacji, zużyciu i szczelności.",exhaust:"Fabryczna konfiguracja właściwa dla wersji silnika.",intake:"Kontrola szczelności i zgodności części.",crank:"Kontrola bicia, luzów i łożysk.",case:"Bez zmian przy serwisie OEM."},
  {id:"derbi-sport",name:"Sport / kit",engine:"Derbi D50B0",family:"Sport",bore:"Zależnie od SKU",note:"Potwierdź kod zestawu, skok, sworzeń i instrukcję.",exhaust:"Tylko wydech potwierdzony dla konkretnego cylindra.",intake:"Zgodność dolotu z zaleceniami producenta.",crank:"Kontrola i dobór zgodnie z wymaganiami zestawu.",case:"Nie obrabiaj bez jednoznacznych zaleceń i pomiarów."},
  {id:"piaggio",name:"Skuter 2T",engine:"Piaggio Hi-Per2",family:"Skuter",bore:"Zależnie od SKU",note:"Uwzględnij wariant silnika, chłodzenie i stan CVT.",exhaust:"Zgodność z cylindrem, chłodzeniem i mocowaniem.",intake:"Weryfikacja membrany, króćca i gaźnika.",crank:"Kontrola i specyfikacja zestawu.",case:"Wyłącznie według dokumentacji konkretnego cylindra."},
  {id:"mh",name:"Minarelli horizontal",engine:"Minarelli poziomy",family:"Skuter",bore:"Zależnie od SKU",note:"Nie przenoś specyfikacji z wersji vertical.",exhaust:"Potwierdzona aplikacja dla wersji horizontal.",intake:"Części zgodne z konkretnym silnikiem.",crank:"Według wymagań cylindra i zakresu obrotów.",case:"Sprawdź dokumentację przed jakąkolwiek zmianą."},
  {id:"mv",name:"Minarelli vertical",engine:"Minarelli pionowy",family:"Skuter",bore:"Zależnie od SKU",note:"Najpierw potwierdź kod silnika i chłodzenie.",exhaust:"Dedykowany do wersji vertical.",intake:"Zgodność z kodem silnika.",crank:"Według dokumentacji zestawu.",case:"Nie zakładaj zgodności z horizontal."},
  {id:"peugeot",name:"Peugeot 2T",engine:"Peugeot 2T",family:"Różne rodziny",bore:"Zależnie od wersji",note:"Marka nie wystarcza do identyfikacji silnika.",exhaust:"Weryfikacja kodu silnika i SKU.",intake:"Według dokładnej rodziny silnika.",crank:"Według specyfikacji producenta.",case:"Wymagana dokumentacja konkretnego zestawu."},
  {id:"dio",name:"Honda Dio AF18 / AF27",engine:"Honda Dio AF18/AF27",family:"Skuter",bore:"Zależnie od wariantu",note:"Potwierdź wersję AF18/AF27 oraz numer cylindra.",exhaust:"Potwierdzona aplikacja dla wariantu.",intake:"Zgodność z kodem silnika.",crank:"Kontrola lub wymiana według specyfikacji.",case:"Nie stosuj uniwersalnych szablonów."},
  {id:"simson",name:"Simson M5x1",engine:"Simson M5x1",family:"Klasyczny 2T",bore:"Zależnie od cylindra",note:"To inna konstrukcja niż typowy silnik AM6.",exhaust:"Zgodność z wersją cylindra i modelem.",intake:"Uwzględnij konstrukcję konkretnego układu dolotowego.",crank:"Dobór według projektu i dokumentacji.",case:"Nie kopiuj specyfikacji z innych platform."}
];
const goals:{id:Goal;title:string;desc:string}[]=[
  {id:"street",title:"Trwałość / spokojna jazda",desc:"Priorytet: stan techniczny, trwałość i zgodność z przepisami."},
  {id:"mid",title:"Szeroki środek obrotów",desc:"Priorytet: spójne dopasowanie wszystkich podzespołów."},
  {id:"race",title:"Projekt torowy",desc:"Priorytet: dane producenta, pomiary i weryfikacja w warsztacie."}
];
const inputClass="mt-1 w-full rounded-lg border border-white/10 bg-[#0b111b] px-3 py-2.5 text-sm text-white outline-none focus:border-sky-500";
const labelClass="block text-xs text-slate-400";
function Field({label,value,onChange,unit="",placeholder="—"}:{label:string;value:string;onChange:(v:string)=>void;unit?:string;placeholder?:string}) {
  return <label className={labelClass}>{label}<div className="relative"><input className={inputClass} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} inputMode="decimal"/>{unit&&<span className="pointer-events-none absolute right-3 top-3 text-xs text-slate-500">{unit}</span>}</div></label>;
}
function PortSketch({selected}:{selected:string}) {
 return <svg viewBox="0 0 340 220" className="w-full" role="img" aria-label="Schemat poglądowy kanałów cylindra, nie w skali"><defs><linearGradient id="metal" x1="0" x2="1"><stop offset="0%" stopColor="#334155"/><stop offset="50%" stopColor="#94a3b8"/><stop offset="100%" stopColor="#334155"/></linearGradient></defs><path d="M75 15 H265 V198 H75Z" fill="url(#metal)" stroke="#94a3b8" strokeWidth="2"/><rect x="112" y="24" width="116" height="163" rx="4" fill="#07111f" stroke="#cbd5e1" strokeWidth="2"/><rect x="126" y="85" width="88" height="30" rx="5" fill={selected==="Wydech"?"#ef4444":"#334155"} stroke="#fca5a5"/><rect x="116" y="135" width="28" height="38" rx="4" fill={selected==="Transfery"?"#22c55e":"#334155"} stroke="#86efac"/><rect x="196" y="135" width="28" height="38" rx="4" fill={selected==="Transfery"?"#22c55e":"#334155"} stroke="#86efac"/><path d="M145 187 Q170 155 195 187" fill={selected==="Dolot"?"#a78bfa":"#334155"} stroke="#c4b5fd"/><g fill="#e2e8f0" fontSize="11"><text x="10" y="91">Wydech</text><text x="10" y="104">schemat</text><text x="236" y="151">Transfery</text><text x="170" y="213" textAnchor="middle" fill="#94a3b8">Poglądowe — nie w skali</text></g><path d="M50 102 H110 M102 96 L110 102 L102 108 M229 150 H274 M267 144 L274 150 L267 156" stroke="#94a3b8" fill="none" strokeWidth="1.5"/></svg>;
}
export default function PortingLabPage(){
 const [engine,setEngine]=useState<Engine>("AM6");
 const [profileId,setProfileId]=useState("am6-sport");
 const [goal,setGoal]=useState<Goal>("street");
 const [channel,setChannel]=useState("Wydech");
 const [projectName,setProjectName]=useState("Mój projekt 2T");
 const [cylinderSku,setCylinderSku]=useState("");
 const [docSource,setDocSource]=useState("");
 const [bore,setBore]=useState("");
 const [stroke,setStroke]=useState("");
 const [squish,setSquish]=useState("");
 const [exhaustBefore,setExhaustBefore]=useState("");
 const [transferBefore,setTransferBefore]=useState("");
 const [intakeBefore,setIntakeBefore]=useState("");
 const [exhaustAfter,setExhaustAfter]=useState("");
 const [transferAfter,setTransferAfter]=useState("");
 const [intakeAfter,setIntakeAfter]=useState("");
 const [notes,setNotes]=useState("");
 const [checks,setChecks]=useState<string[]>([]);
 const [saved,setSaved]=useState(false);
 const [showMath,setShowMath]=useState(false);
 const filtered=useMemo(()=>profiles.filter(p=>p.engine===engine),[engine]);
 const profile=filtered.find(p=>p.id===profileId)??filtered[0];
 const readiness=[
  {id:"identity",text:"Potwierdzony kod silnika, cylinder i dokładny numer katalogowy"},
  {id:"manual",text:"Dostępna instrukcja producenta dla tej konkretnej wersji"},
  {id:"baseline",text:"Zapisany stan wyjściowy i pomiary wykonane odpowiednimi przyrządami"},
  {id:"health",text:"Sprawdzony stan cylindra, tłoka, pierścieni, wału i łożysk"},
  {id:"seal",text:"Zaplanowana kontrola szczelności i montażu po pracach"},
  {id:"expert",text:"Ustalona weryfikacja projektu z doświadczonym warsztatem 2T"}
 ];
 const measurements=[{name:"Wydech",before:exhaustBefore,after:exhaustAfter,setBefore:setExhaustBefore,setAfter:setExhaustAfter},{name:"Transfery",before:transferBefore,after:transferAfter,setBefore:setTransferBefore,setAfter:setTransferAfter},{name:"Dolot / ssanie",before:intakeBefore,after:intakeAfter,setBefore:setIntakeBefore,setAfter:setIntakeAfter}];
 const num=(v:string)=>v.trim()===""?null:Number(v.replace(",","."));
 const diff=(a:string,b:string)=>{const x=num(a),y=num(b);return x!==null&&y!==null&&Number.isFinite(x)&&Number.isFinite(y)?(y-x).toFixed(1):"—"};
 const ready=checks.length;
 const report=()=>[
  "MOTOHUB PORTING LAB — KARTA PLANU",
  "Projekt: "+projectName,
  "Silnik: "+engine,
  "Profil: "+profile.name+" ("+profile.family+")",
  "Cel: "+goals.find(g=>g.id===goal)?.title,
  "SKU cylindra: "+(cylinderSku||"nie wpisano"),
  "Źródło dokumentacji: "+(docSource||"nie wpisano"),
  "Średnica: "+(bore||"—")+" mm; skok: "+(stroke||"—")+" mm; squish: "+(squish||"—")+" mm",
  "Pomiary — wartości wpisane przez użytkownika (nie są zaleceniami obróbki):",
  ...measurements.map(m=>m.name+": przed "+(m.before||"—")+"°; po/plan "+(m.after||"—")+"°; różnica "+diff(m.before,m.after)+"°"),
  "Kontrola gotowości: "+ready+"/"+readiness.length,
  "Notatki: "+(notes||"—"),
  "Uwaga: to karta pomiarowa, nie instrukcja frezowania ani gwarancja bezpiecznych wymiarów."
 ].join("\n");
 const saveProject=()=>{try{localStorage.setItem("motohub-porting-lab",JSON.stringify({projectName,engine,profileId,goal,channel,cylinderSku,docSource,bore,stroke,squish,exhaustBefore,transferBefore,intakeBefore,exhaustAfter,transferAfter,intakeAfter,notes,checks}));setSaved(true)}catch{setSaved(false)}};
 useEffect(()=>{try{const raw=localStorage.getItem("motohub-porting-lab");if(raw){const p=JSON.parse(raw);if(p.projectName)setProjectName(p.projectName);if(p.engine&&profiles.some(x=>x.engine===p.engine)){setEngine(p.engine);if(p.profileId)setProfileId(p.profileId)}if(p.goal)setGoal(p.goal);if(p.channel)setChannel(p.channel);for(const k of ["cylinderSku","docSource","bore","stroke","squish","exhaustBefore","transferBefore","intakeBefore","exhaustAfter","transferAfter","intakeAfter","notes"] as const)if(typeof p[k]==="string")({cylinderSku:setCylinderSku,docSource:setDocSource,bore:setBore,stroke:setStroke,squish:setSquish,exhaustBefore:setExhaustBefore,transferBefore:setTransferBefore,intakeBefore:setIntakeBefore,exhaustAfter:setExhaustAfter,transferAfter:setTransferAfter,intakeAfter:setIntakeAfter,notes:setNotes}[k] as (v:string)=>void)(p[k]);if(Array.isArray(p.checks))setChecks(p.checks)}}catch{/* damaged local draft is ignored */}},[]);
 const download=()=>{const blob=new Blob([report()],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="motohub-porting-plan.txt";a.click();URL.revokeObjectURL(url)};
 return <main className="min-h-screen bg-[#060b13] text-slate-100"><div className="mx-auto max-w-[1500px] px-4 py-5 sm:px-6 lg:px-8"><SiteNav/>
  <div className="mt-7 flex flex-wrap items-start justify-between gap-4"><div><Link href="/narzedzia" className="text-sm text-slate-500 hover:text-white">← Narzędzia</Link><p className="mt-4 text-xs font-bold uppercase tracking-[.28em] text-sky-400">MotoHub / Engineering workspace</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Porting Lab <span className="text-sky-400">2T</span></h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Zaawansowana karta projektu: identyfikacja cylindra, dane źródłowe, pomiary przed/po, lista gotowości i raport do wydruku. Nie generuje wymiarów cięcia ani szablonów frezowania.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>window.print()} className="rounded-lg border border-white/10 px-4 py-2.5 text-sm hover:bg-white/5">Drukuj / PDF</button><button onClick={download} className="rounded-lg border border-sky-500/50 bg-sky-500/10 px-4 py-2.5 text-sm font-bold text-sky-200 hover:bg-sky-500/20">Eksportuj plan</button><button onClick={saveProject} className="rounded-lg bg-sky-500 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-sky-400">Zapisz projekt</button></div></div>
  {saved&&<p className="mt-3 text-xs text-emerald-300" role="status">Szkic zapisany lokalnie w tej przeglądarce.</p>}
  <div className="mt-6 grid gap-4 xl:grid-cols-[minmax(250px,.78fr)_minmax(400px,1.45fr)_minmax(250px,.78fr)]">
   <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-base font-bold">01 / Konfiguracja</h2><div className="mt-4 space-y-4">
    <label className={labelClass}>Nazwa projektu<input className={inputClass} value={projectName} onChange={e=>setProjectName(e.target.value)}/></label>
    <label className={labelClass}>Platforma<select className={inputClass} value={engine} onChange={e=>{const next=e.target.value as Engine;setEngine(next);setProfileId(profiles.find(p=>p.engine===next)!.id);setChecks([])}}>{Array.from(new Set(profiles.map(p=>p.engine))).map(x=><option key={x}>{x}</option>)}</select></label>
    <label className={labelClass}>Cylinder / klasa<select className={inputClass} value={profile.id} onChange={e=>{setProfileId(e.target.value);setChecks([])}}>{filtered.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label className={labelClass}>Numer katalogowy cylindra<input className={inputClass} value={cylinderSku} onChange={e=>setCylinderSku(e.target.value)} placeholder="Producent / SKU / wersja"/></label>
    <label className={labelClass}>Źródło danych<input className={inputClass} value={docSource} onChange={e=>setDocSource(e.target.value)} placeholder="Instrukcja, numer strony, link…"/></label>
    <div><p className={labelClass}>Cel projektu</p><div className="mt-2 space-y-2">{goals.map(g=><button key={g.id} onClick={()=>setGoal(g.id)} className={"w-full rounded-xl border p-3 text-left "+(goal===g.id?"border-sky-400/60 bg-sky-400/10":"border-white/10 bg-black/20")}><span className="text-sm font-semibold">{g.title}</span><span className="mt-1 block text-xs leading-5 text-slate-400">{g.desc}</span></button>)}</div></div>
    <div className="rounded-xl border border-white/10 p-3"><p className="text-xs font-bold text-slate-300">Profil wybranego cylindra</p><p className="mt-2 text-xs leading-5 text-slate-400">{profile.note}</p></div>
   </div></section>
   <div className="space-y-4">
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold">02 / Schemat i obszar</h2><span className="rounded-full border border-amber-400/30 px-2.5 py-1 text-[10px] font-bold text-amber-200">POGLĄDOWE</span></div><div className="grid gap-3 md:grid-cols-[1fr_.9fr]"><div className="rounded-xl bg-[#07101c] p-3"><PortSketch selected={channel}/></div><div><p className="text-xs text-slate-400">Obszar analizy</p><div className="mt-2 grid grid-cols-3 gap-2">{["Wydech","Transfery","Dolot"].map(x=><button key={x} onClick={()=>setChannel(x)} className={"rounded-lg border px-2 py-3 text-xs font-bold "+(channel===x?"border-sky-400/60 bg-sky-400/10 text-sky-200":"border-white/10 text-slate-400")}>{x}</button>)}</div><p className="mt-4 text-sm leading-6 text-slate-300">{channel==="Wydech"?"Rejestruj istniejące dane fazy wydechu i porównuj je z dokumentacją dokładnego cylindra.":channel==="Transfery"?"Zapisz osobno dane kanałów transferowych; różnice między kanałami powinny być sprawdzone w dokumentacji i przez specjalistę.":"Najpierw zidentyfikuj sposób sterowania dolotem — konstrukcje 2T różnią się między platformami."}</p><p className="mt-4 text-xs leading-5 text-slate-500">Ilustracja jest schematyczna, nie przedstawia wymiarów rzeczywistego cylindra i nie może służyć jako wzornik.</p></div></div></section>
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-base font-bold">03 / Karta pomiarowa</h2><p className="mt-1 text-xs leading-5 text-slate-500">Wpisuj tylko rzeczywiście zmierzone lub udokumentowane wartości. Kolumna „po / plan” służy do zapisu danych po profesjonalnej weryfikacji, a nie jako cel cięcia.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Średnica cylindra" value={bore} onChange={setBore} unit="mm" placeholder="zmierzona"/><Field label="Skok wału" value={stroke} onChange={setStroke} unit="mm" placeholder="dokumentacja"/><Field label="Squish" value={squish} onChange={setSquish} unit="mm" placeholder="zmierzony"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="text-slate-400"><tr><th className="border-b border-white/10 p-2">Obszar</th><th className="border-b border-white/10 p-2">Przed (°)</th><th className="border-b border-white/10 p-2">Po / plan (°)</th><th className="border-b border-white/10 p-2">Różnica</th></tr></thead><tbody>{measurements.map(m=><tr key={m.name}><td className="border-b border-white/5 p-2 font-semibold text-slate-200">{m.name}</td><td className="border-b border-white/5 p-2"><input className="w-24 rounded-md border border-white/10 bg-black/20 px-2 py-2" inputMode="decimal" value={m.before} onChange={e=>m.setBefore(e.target.value)} placeholder="—"/></td><td className="border-b border-white/5 p-2"><input className="w-24 rounded-md border border-white/10 bg-black/20 px-2 py-2" inputMode="decimal" value={m.after} onChange={e=>m.setAfter(e.target.value)} placeholder="—"/></td><td className="border-b border-white/5 p-2 font-mono text-sky-300">{diff(m.before,m.after)}°</td></tr>)}</tbody></table></div><button onClick={()=>setShowMath(v=>!v)} className="mt-3 text-xs text-sky-300 underline underline-offset-4">{showMath?"Ukryj opis pomiarów":"Jak interpretować te pola?"}</button>{showMath&&<div className="mt-3 rounded-xl bg-black/20 p-3 text-xs leading-5 text-slate-400">Różnica to wyłącznie odejmowanie wpisanych wartości „przed” od „po / plan”. Nie jest rekomendacją i nie określa, czy dana faza jest bezpieczna. Porównuj wartości tylko z wiarygodną dokumentacją dla dokładnego SKU, a pomiary potwierdź przyrządami i przez osobę z doświadczeniem.</div>}</section>
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-base font-bold">04 / Notatki techniczne</h2><textarea className="mt-3 min-h-28 w-full rounded-xl border border-white/10 bg-[#07101c] p-3 text-sm leading-6 text-white outline-none focus:border-sky-500" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Stan cylindra, numery części, źródło danych, pytania do warsztatu, uwagi po kontroli…"/><div className="mt-3 flex flex-wrap gap-2"><button onClick={saveProject} className="rounded-lg bg-sky-500 px-3 py-2 text-xs font-bold text-slate-950">Zapisz lokalnie</button><button onClick={download} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">Pobierz kartę TXT</button><button onClick={()=>{setProjectName("Mój projekt 2T");setCylinderSku("");setDocSource("");setBore("");setStroke("");setSquish("");setExhaustBefore("");setTransferBefore("");setIntakeBefore("");setExhaustAfter("");setTransferAfter("");setIntakeAfter("");setNotes("");setChecks([]);setSaved(false)}} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-slate-400">Wyczyść formularz</button></div></section>
   </div>
   <aside className="space-y-4">
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-base font-bold">05 / Gotowość projektu</h2><p className="mt-1 text-xs leading-5 text-slate-400">Lista przygotowania i kontroli — nie jest zgodą na samodzielną obróbkę.</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-400 transition-all" style={{width:(ready/readiness.length*100)+"%"}}/></div><p className="mt-2 text-xs text-sky-200">{ready} z {readiness.length} punktów odnotowanych</p><div className="mt-3 space-y-3">{readiness.map(r=><label key={r.id} className="flex gap-2 text-xs leading-5 text-slate-300"><input type="checkbox" checked={checks.includes(r.id)} onChange={e=>setChecks(old=>e.target.checked?[...old,r.id]:old.filter(x=>x!==r.id))} className="mt-1 accent-sky-400"/><span>{r.text}</span></label>)}</div></section>
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-base font-bold">06 / Zgodność podzespołów</h2><div className="mt-3 space-y-3">{[{t:"Wydech",d:profile.exhaust},{t:"Dolot",d:profile.intake},{t:"Wał i łożyska",d:profile.crank},{t:"Kartery",d:profile.case}].map(x=><div key={x.t} className="border-b border-white/5 pb-3 last:border-0"><p className="text-xs font-bold text-sky-200">{x.t}</p><p className="mt-1 text-xs leading-5 text-slate-400">{x.d}</p></div>)}</div></section>
    <section className="rounded-2xl border border-amber-400/20 bg-amber-400/[.04] p-4"><h2 className="text-sm font-bold text-amber-100">Granice bezpieczeństwa</h2><ul className="mt-2 space-y-2 text-xs leading-5 text-amber-100/75"><li>• Nie ma uniwersalnych wymiarów dla całej rodziny silników.</li><li>• Nie używaj schematu jako szablonu do obróbki.</li><li>• Błędna obróbka może osłabić tuleję, uszkodzić pierścienie lub doprowadzić do awarii.</li><li>• Zmiany w pojeździe drogowym muszą być zgodne z przepisami.</li></ul></section>
    <section className="rounded-2xl border border-white/10 bg-[#0b1320] p-4"><h2 className="text-sm font-bold">Następne kroki</h2><ol className="mt-3 space-y-2 text-xs leading-5 text-slate-400"><li>1. Zidentyfikuj dokładny cylinder i numer katalogowy.</li><li>2. Zapisz źródło danych i stan wyjściowy.</li><li>3. Uzupełnij tylko zweryfikowane pomiary.</li><li>4. Skonsultuj zakres zmian z warsztatem 2T.</li><li>5. Po pracach zleć kontrolę, montaż i testy.</li></ol><Link href="/narzedzia/setupy-2t" className="mt-4 block rounded-lg border border-white/10 px-3 py-2.5 text-center text-xs font-bold hover:bg-white/5">Baza setupów 2T →</Link><Link href="/narzedzia/tuning-2t" className="mt-2 block rounded-lg border border-white/10 px-3 py-2.5 text-center text-xs font-bold hover:bg-white/5">Symulator mocy →</Link></section>
   </aside>
  </div>
 </div><style jsx global>{`@media print{body{background:#fff!important;color:#111!important}main{background:#fff!important;color:#111!important}button,a,nav{display:none!important}section{break-inside:avoid;border-color:#ccc!important;background:#fff!important}input,textarea{color:#111!important;border-color:#ccc!important}p,h1,h2,h3,td,th,label,span{color:#111!important}}`}</style></main>;
}
