"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import SiteNav from "../../SiteNav";

type Engine = "AM6" | "Derbi D50B0" | "Piaggio Hi-Per2" | "Minarelli poziomy" | "Minarelli pionowy" | "Peugeot 2T" | "Honda Dio AF18/AF27" | "Simson M5x1";
type Goal = "street" | "mid" | "race";
type PortProfile = {
  id: string; name: string; engine: Engine; bore: string; className: string; goal: Goal;
  summary: string; exhaust: string; intake: string; crank: string; case: string; limits: string[];
};
const profiles: PortProfile[] = [
  { id:"am6-oem", name:"Cylinder OEM 50", engine:"AM6", bore:"50 cm³", className:"OEM", goal:"street", summary:"Do serwisu i zachowania fabrycznej charakterystyki. Porting nie jest domyślnie potrzebny.", exhaust:"Seryjny, homologowany i zgodny z modelem.", intake:"Seryjny dolot w dobrym stanie; najpierw szczelność.", crank:"Wał OEM po kontroli luzów, bicia i łożysk.", case:"Nie powiększać kanałów przy serwisie.", limits:["Zachowaj fabryczne fazy i kształt kanałów.","Napraw nieszczelności zamiast kompensować je obróbką.","Weryfikuj wymiary w instrukcji serwisowej."] },
  { id:"am6-sport", name:"50–70 cm³ Sport", engine:"AM6", bore:"50–70 cm³ zależnie od kitu", className:"Sport", goal:"street", summary:"Dla wielu gotowych cylindrów sportowych najpierw warto poprawnie dobrać osprzęt, a nie obrabiać cylinder.", exhaust:"Wydech z potwierdzoną aplikacją do dokładnego SKU cylindra.", intake:"Seryjny sprawny lub kompatybilny zestaw membrany/króćca.", crank:"OEM tylko po rzetelnej kontroli; wzmacniany, gdy wymaga go producent cylindra.", case:"Zwykle bez obróbki w zestawie plug-and-play, ale instrukcja konkretnego SKU ma pierwszeństwo.", limits:["Porównaj dokumentację cylindra z pomiarami rzeczywistej sztuki.","Nie zmieniaj wysokości kanałów bez wyznaczonego celu i pomiarów faz.","Zacznij od stanu technicznego i poprawnego montażu."] },
  { id:"am6-86", name:"Klasa 80–86 cm³ / high-end", engine:"AM6", bore:"Zależne od konkretnego cylindra i skoku", className:"High-end", goal:"race", summary:"Wysokie obciążenia i obroty. Nie istnieje uniwersalny szablon portingu dla całej klasy pojemności.", exhaust:"Komora dobrana do dokładnego cylindra i charakterystyki wymaganej przez producenta.", intake:"Membrana, króciec i gaźnik zgodne z kartą techniczną konkretnego zestawu.", crank:"Zwykle wymagany odpowiednio dobrany wzmacniany wał i łożyskowanie; potwierdź zakres obrotów.", case:"Może wymagać dopasowania, ale decyzję podejmuje się z dokumentacji i pomiaru karterów.", limits:["Przed obróbką potwierdź SKU, skok, squish i fazy rozrządu.","Nie używaj rysunku z innego cylindra jako szablonu.","Pomiary i obróbkę powierz specjaliście od silników 2T."] },
  { id:"derbi-oem", name:"Cylinder OEM 50", engine:"Derbi D50B0", bore:"50 cm³", className:"OEM", goal:"street", summary:"Konfiguracja do odnowienia seryjnego silnika; priorytetem są szczelność, stan cylindra i poprawny montaż.", exhaust:"Seryjny wydech zgodny z modelem i normą emisji.", intake:"Fabryczna membrana i gaźnik w stanie zgodnym ze specyfikacją.", crank:"OEM po kontroli bicia, luzów i łożysk.", case:"Bez flow przy serwisie seryjnego cylindra.", limits:["Nie odtwarzaj wymiarów na podstawie zdjęć.","Porównaj cylinder z danymi serwisowymi konkretnej wersji.","Sprawdź szczelność skrzyni korbowej."] },
  { id:"derbi-sport", name:"Sport 50–70 cm³", engine:"Derbi D50B0", bore:"Zależnie od zestawu", className:"Sport", goal:"street", summary:"W gotowym zestawie sportowym porting nie musi być wymagany. Dopasowanie części zależy od numeru katalogowego.", exhaust:"Wydech z potwierdzoną aplikacją dla D50B0 i wybranego cylindra.", intake:"Seryjny sprawny lub zestaw wskazany przez producenta.", crank:"Kontrola OEM; wał wzmacniany, jeśli wymagają tego cylinder i jego obroty.", case:"Nie obrabiać bez wskazania producenta i pomiarów.", limits:["Sprawdź kompatybilność D50B0, skoku i sworznia.","Ustal docelowy zakres obrotów na podstawie dokumentacji.","Nie usuwaj materiału z mostków i krawędzi bez analizy specjalisty."] },
  { id:"piaggio-sport", name:"Skuter Sport 50–70 cm³", engine:"Piaggio Hi-Per2", bore:"Zależnie od cylindra", className:"Sport", goal:"street", summary:"W skuterze osiągi zależą także od CVT, chłodzenia i dopasowania wydechu.", exhaust:"Wydech do dokładnego cylindra, wariantu chłodzenia i mocowania.", intake:"Membrana i króciec zgodne z konkretnym silnikiem.", crank:"OEM po kontroli lub wał wskazany przez producenta cylindra.", case:"Flow tylko gdy wymaga go instrukcja i potwierdzają to pomiary.", limits:["Nie zakładaj, że zestaw do innego silnika Piaggio pasuje.","Sprawdź chłodzenie i stan napędu CVT.","Porting nie zastępuje właściwego doboru cylindra i wydechu."] },
  { id:"minarelli-horizontal", name:"Minarelli horizontal Sport", engine:"Minarelli poziomy", bore:"50–70 cm³ zależnie od zestawu", className:"Sport", goal:"street", summary:"Wybieraj cylinder i wydech dla konkretnej wersji horizontal oraz chłodzenia.", exhaust:"Komora z potwierdzoną aplikacją do danego cylindra.", intake:"Seryjny lub zgodny z zestawem membrany i króćca.", crank:"OEM po kontroli dla łagodnego kitu; mocniejszy według specyfikacji zestawu.", case:"Zwykle nie w zestawie plug-and-play, jeśli producent nie wymaga inaczej.", limits:["Nie przenoś ustawień z Minarelli vertical.","Używaj dokumentacji konkretnego producenta.","Nie obrabiaj kanałów bez pomiarów i doświadczenia."] },
  { id:"minarelli-vertical", name:"Minarelli vertical", engine:"Minarelli pionowy", bore:"Zależnie od wersji", className:"OEM / Sport", goal:"street", summary:"Oddzielna rodzina silnika — dobór cylindra i wydechu musi uwzględniać wersję pionową.", exhaust:"Wydech przeznaczony do Minarelli vertical i konkretnego cylindra.", intake:"Zgodna membrana/króciec dla tej rodziny silnika.", crank:"OEM po kontroli lub zgodny wał według dokumentacji zestawu.", case:"Nie zakładaj kompatybilności karterów z wersją poziomą.", limits:["Potwierdź kod silnika i chłodzenie.","Zweryfikuj katalog części.","Nie kopiuj wymiarów z innych platform."] },
  { id:"peugeot", name:"Peugeot 2T", engine:"Peugeot 2T", bore:"Zależnie od rodziny silnika", className:"Platforma", goal:"street", summary:"Oznaczenie Peugeot obejmuje różne wersje. Najpierw zidentyfikuj kod silnika.", exhaust:"Dedykowany do konkretnego silnika, chłodzenia i mocowań.", intake:"Gaźnik i membrana dobrane do dokładnej rodziny silnika.", crank:"Wał o zgodnych wymiarach i parametrach producenta.", case:"Decyzja wyłącznie na podstawie instrukcji konkretnego zestawu.", limits:["Odczytaj kod silnika i rocznik.","Nie dobieraj po samej marce skutera.","Obróbkę powierz specjaliście z dokumentacją."] },
  { id:"honda-dio", name:"Honda Dio AF18 / AF27", engine:"Honda Dio AF18/AF27", bore:"50 cm³ / kit zależny od wariantu", className:"Skuter", goal:"street", summary:"AF18 i AF27 wymagają potwierdzenia konkretnego wariantu i katalogu części.", exhaust:"Wydech potwierdzony dla rodziny silnika i ramy.", intake:"Dolot zgodny z kodem silnika i zestawem.", crank:"OEM po kontroli lub wał wymieniony zgodnie z instrukcją cylindra.", case:"Nie przy serwisie OEM; przy big-bore tylko według dokumentacji zestawu.", limits:["Potwierdź kod silnika.","Sprawdź kompatybilność cylindra, wału i chłodzenia.","Nie stosuj uniwersalnego szablonu portingu."] },
  { id:"simson", name:"Simson M5x1", engine:"Simson M5x1", bore:"Zależnie od modelu i cylindra", className:"OEM / projekt", goal:"street", summary:"Seryjny Simson ma inny układ dolotu niż typowy silnik AM6; nie przenoś schematów między konstrukcjami.", exhaust:"Wydech zgodny z wersją cylindra i modelem.", intake:"Układ zgodny z konstrukcją silnika; nie zakładaj typowej membrany AM6.", crank:"OEM po kontroli lub część dobrana do konkretnego projektu.", case:"Nie przy serwisie OEM; modyfikacje wymagają dokumentacji.", limits:["Zidentyfikuj dokładny cylinder i jego producenta.","Użyj dedykowanej dokumentacji dla M5x1.","Pomiar faz i weryfikacja przez specjalistę."] }
];

const goals: {id:Goal; title:string; desc:string}[] = [
  { id:"street", title:"Ulica / trwałość", desc:"Płynna charakterystyka, trwałość i zgodność z przepisami." },
  { id:"mid", title:"Środek obrotów", desc:"Kompromis elastyczności i zakresu pracy." },
  { id:"race", title:"Tor / wysoki zakres obrotów", desc:"Projekt wymagający dokładnych danych cylindra i pomiarów." }
];
const channelNames = [
  { id:"exhaust", label:"Kanał wydechowy", desc:"Najsilniej wpływa na fazę wydechu i dopasowanie komory." },
  { id:"transfers", label:"Kanały transferowe", desc:"Wpływają na przepływ mieszanki i charakterystykę napełniania." },
  { id:"intake", label:"Dolot / ssanie", desc:"Zależy od konstrukcji sterowania dolotem; nie każdy silnik ma ten sam układ." }
];

function PortSketch({ goal, selected }: { goal:Goal; selected:string }) {
  const width = goal === "race" ? 116 : goal === "mid" ? 106 : 96;
  const height = goal === "race" ? 66 : goal === "mid" ? 60 : 54;
  return <svg viewBox="0 0 320 190" className="w-full" role="img" aria-label="Poglądowy przekrój kanałów cylindra, nie w skali">
    <defs><linearGradient id="metal" x1="0" x2="1"><stop offset="0%" stopColor="#52525b"/><stop offset="45%" stopColor="#a1a1aa"/><stop offset="100%" stopColor="#3f3f46"/></linearGradient></defs>
    <path d="M65 18 H255 V170 H65 Z" fill="url(#metal)" stroke="#71717a" strokeWidth="2"/>
    <rect x="105" y="22" width="110" height="146" rx="3" fill="#18181b" stroke="#d4d4d8" strokeWidth="2"/>
    <path d={`M105 105 Q160 ${105-height} 215 105 L215 132 Q160 ${132-height*0.35} 105 132 Z`} fill={selected === "exhaust" ? "#ef4444" : "#71717a"} stroke="#fca5a5" strokeWidth="1.5"/>
    <path d={`M105 145 Q130 ${145-height*0.3} 145 145 L145 158 H105 Z`} fill={selected === "transfers" ? "#f59e0b" : "#52525b"}/>
    <path d={`M175 145 Q190 ${145-height*0.3} 215 145 V158 H175 Z`} fill={selected === "transfers" ? "#f59e0b" : "#52525b"}/>
    <path d="M40 96 H88 M80 89 L88 96 L80 103" stroke="#d4d4d8" strokeWidth="2" fill="none"/>
    <text x="14" y="85" fill="#e4e4e7" fontSize="10">Przekrój</text><text x="14" y="98" fill="#e4e4e7" fontSize="10">poglądowy</text>
    <text x="160" y="181" textAnchor="middle" fill="#a1a1aa" fontSize="10">Schematic / nie w skali</text>
  </svg>;
}

export default function PortingLabPage() {
  const [engine, setEngine] = useState<Engine>("AM6");
  const [goal, setGoal] = useState<Goal>("street");
  const [cylinder, setCylinder] = useState("am6-sport");
  const [channel, setChannel] = useState("exhaust");
  const [notes, setNotes] = useState("");
  const [checked, setChecked] = useState<string[]>([]);
  const [showHelp, setShowHelp] = useState(false);
  const filtered = useMemo(() => profiles.filter(p => p.engine === engine), [engine]);
  const selected = filtered.find(p => p.id === cylinder) ?? filtered[0];
  const chosenGoal = goals.find(g => g.id === goal)!;
  const guidance = goal === "street"
    ? ["Zachowaj fabryczne fazy i kształty, jeśli nie ma danych producenta.", "Najpierw sprawdź zużycie cylindra, tłoka, pierścieni i szczelność skrzyni korbowej.", "W gotowym cylindrze sportowym sprawdź, czy producent w ogóle dopuszcza porting."]
    : goal === "mid"
    ? ["Zdefiniuj zakres obrotów na podstawie dokumentacji cylindra i wydechu.", "Zapisz pomiary aktualnych faz i porównaj je z danymi producenta.", "Nie podnoś ani nie poszerzaj kanałów bez sprawdzenia pierścieni, mostków i grubości tulei."]
    : ["Przed pracą potwierdź SKU, geometrię, fazy, squish i zakres obrotów.", "Wysokoobrotowy cylinder wymaga zgodnego wału, łożyskowania, chłodzenia i wydechu.", "Porting i flow karterów powierz warsztatowi, który mierzy fazy i kontroluje grubość materiału."];
  return <main className="min-h-screen bg-[#090909] text-white"><div className="mx-auto max-w-7xl px-5 py-5 lg:px-8"><SiteNav />
    <div className="mt-8"><Link href="/narzedzia" className="text-sm text-zinc-500 hover:text-white">← Narzędzia</Link><p className="mt-5 text-xs font-black uppercase tracking-[.3em] text-red-500">MotoHub / 2T Engineering</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Porting Lab</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">Interaktywny przewodnik do planowania portingu. Wybierz platformę, klasę cylindra, cel i kanał, aby zobaczyć poglądową sekcję oraz checklistę pomiarową. Rysunek jest schematyczny — nie stanowi szablonu obróbki.</p></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
      <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="text-lg font-bold">1. Konfiguracja projektu</h2>
        <label className="mt-4 block text-xs text-zinc-400">Silnik<select value={engine} onChange={e => {const next=e.target.value as Engine;setEngine(next);setCylinder(profiles.find(p=>p.engine===next)!.id);setChecked([])}} className="mt-2 w-full rounded-xl border border-white/10 bg-[#111] px-3 py-3 text-sm text-white">{Array.from(new Set(profiles.map(p=>p.engine))).map(e=><option key={e} value={e}>{e}</option>)}</select></label>
        <label className="mt-4 block text-xs text-zinc-400">Cylinder / klasa<select value={selected.id} onChange={e=>{setCylinder(e.target.value);setChecked([])}} className="mt-2 w-full rounded-xl border border-white/10 bg-[#111] px-3 py-3 text-sm text-white">{filtered.map(p=><option key={p.id} value={p.id}>{p.name} · {p.className}</option>)}</select></label>
        <div className="mt-5"><p className="text-xs text-zinc-400">2. Oczekiwany charakter</p><div className="mt-2 grid gap-2">{goals.map(g=><button key={g.id} type="button" onClick={()=>setGoal(g.id)} className={`rounded-xl border p-3 text-left ${goal===g.id?"border-red-500/50 bg-red-500/10":"border-white/10 bg-black/20"}`}><span className="text-sm font-semibold">{g.title}</span><span className="mt-1 block text-xs text-zinc-400">{g.desc}</span></button>)}</div></div>
        <div className="mt-5"><p className="text-xs text-zinc-400">3. Wybierz obszar</p><div className="mt-2 grid gap-2">{channelNames.map(ch=><button key={ch.id} type="button" onClick={()=>setChannel(ch.id)} className={`rounded-xl border p-3 text-left ${channel===ch.id?"border-red-500/50 bg-red-500/10":"border-white/10 bg-black/20"}`}><span className="text-sm font-semibold">{ch.label}</span><span className="mt-1 block text-xs text-zinc-400">{ch.desc}</span></button>)}</div></div>
      </section>
      <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Wizualizacja kanałów</h2><span className="rounded-full border border-amber-500/20 bg-amber-500/5 px-3 py-1 text-[10px] font-bold text-amber-200">POGLĄDOWA</span></div><PortSketch goal={goal} selected={channel}/><p className="text-sm leading-6 text-zinc-300">{selected.summary}</p>
        <div className="mt-4 grid gap-3 sm:grid-cols-2">{[{title:"Wydech",text:selected.exhaust},{title:"Dolot",text:selected.intake},{title:"Wał",text:selected.crank},{title:"Kartery",text:selected.case}].map(item=><div key={item.title} className="rounded-xl border border-white/5 bg-black/20 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-red-300">{item.title}</p><p className="mt-2 text-xs leading-5 text-zinc-300">{item.text}</p></div>)}</div>
        <div className="mt-5 rounded-xl border border-white/10 p-4"><h3 className="font-bold">Kierunek dla celu: {chosenGoal.title}</h3><p className="mt-1 text-xs text-zinc-400">{chosenGoal.desc}</p><ul className="mt-3 space-y-2">{guidance.map(g=><li key={g} className="flex gap-2 text-xs leading-5 text-zinc-300"><span className="text-red-400">•</span>{g}</li>)}</ul></div>
        <div className="mt-5"><h3 className="font-bold">Lista kontrolna przed decyzją</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{selected.limits.map(item=><label key={item} className="flex gap-2 rounded-xl border border-white/5 p-3 text-xs leading-5 text-zinc-300"><input type="checkbox" checked={checked.includes(item)} onChange={e=>setChecked(old=>e.target.checked?[...old,item]:old.filter(v=>v!==item))} className="mt-1 accent-red-500"/><span>{item}</span></label>)}</div><p className="mt-3 text-xs text-zinc-500">Odznaczono: {checked.length} / {selected.limits.length}</p></div>
        <div className="mt-5"><label className="block text-xs text-zinc-400">Notatki / numer katalogowy / zmierzone dane<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Zapisz kod silnika, SKU cylindra, źródło dokumentacji i pomiary…" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-3 py-3 text-sm text-white outline-none focus:border-red-500/50"/></label><button type="button" onClick={()=>setShowHelp(v=>!v)} className="mt-3 rounded-xl border border-white/10 px-4 py-2 text-xs font-bold hover:bg-white/5">{showHelp?"Ukryj objaśnienia":"Jak czytać plan?"}</button>{showHelp&&<p className="mt-3 rounded-xl bg-black/30 p-3 text-xs leading-5 text-zinc-400">To narzędzie pomaga przygotować rozmowę z warsztatem i porównać cele. Nie wylicza bezpiecznych wymiarów portów na podstawie samej pojemności, ponieważ do tego potrzebne są dokładne dane cylindra, skok, geometria i pomiary. Nie używaj schematu jako wzornika do frezowania.</p>}</div>
      </section>
    </div>
    <div className="mt-5 rounded-2xl border border-amber-500/20 bg-amber-500/[.04] p-4 text-xs leading-5 text-amber-100/80"><b>Bezpieczeństwo:</b> wizualizacja jest poglądowa, nie w skali. Nie zawiera wymiarów ani szablonów obróbki. Usunięcie materiału może osłabić tuleję, uszkodzić pierścienie lub doprowadzić do zatarcia. Dokładne prace wymagają dokumentacji konkretnego cylindra, pomiarów i kompetentnego warsztatu. Sprawdź przepisy dotyczące dopuszczenia pojazdu do ruchu.</div>
    <div className="mt-5 flex flex-wrap gap-3"><Link href="/narzedzia/setupy-2t" className="rounded-xl bg-red-500 px-4 py-3 text-sm font-bold hover:bg-red-400">Baza setupów 2T →</Link><Link href="/narzedzia/kalkulator" className="rounded-xl border border-white/10 px-4 py-3 text-sm font-bold text-zinc-300 hover:bg-white/5">Kalkulator wydechu →</Link></div>
  </div></main>;
}
